---
- hosts: controlplane
  become: true

  roles:
    - role: controlplane
      tags: controlplane

- hosts: controlplane, workers
  become: true

  tasks:
    - name: acquire rke2 node token
      shell: |
        cat /var/lib/rancher/rke2/server/node-token
      register: rke2_node_token
      delegate_to: master
    - name: acquire master node private ip
      uri:
        url: http://169.254.169.254/latest/meta-data/local-ipv4
        return_content: true
      register: master_private_ip
      delegate_to: master
      failed_when: master_private_ip is not defined or master_private_ip.status != 200
    - name: register ansible facts required by worker nodes
      set_fact:
        rke2_node_token: "{{ rke2_node_token.stdout }}"
        master_private_ip: "{{ master_private_ip.content }}"

- hosts: workers
  become: true

  roles:
    - role: worker
      tags: worker
